### ISSUE TITLE
not able to download more than 5 pages 

### ISSUE THREAD

**Issue by rinkal26783** [kovleventer/WenkuBaiduDL#1]
using following command i am only able to download 5 pages.

python wenku_baidu_dl.py "https://wenku.baidu.com/view/12753c401611cc7931b765ce05087632311274cd.html" -o result.pdf -r 480 -p 10

document has 139 pages. how can i download them all?

**Comment by kovleventer** [comment]
It seems like your document is behind a paywall and I also could get only the first five pages manually (on the website). There is no way to get around this using their API, you have to either buy this document, or find it somewhere else.

**Comment by kovleventer** [comment]
An error message is now displayed when the document can not be properly downloaded.
